### PR TITLE
Updated the behaviour of table aliasing

### PR DESCRIPTION
**Pull request by PaulGrimshaw**
Please note, this could have breaking changes for uses where the old form of aliasing was used

### CODE REVIEW

**Comment by jrf0110** [comment]
Awesome. That was fast :)

I'll have to give this a proper once over later today, but everything looks good to me.

**Comment by PaulGrimshaw** [comment]
Hi, any idea when you'll be able to patch this in? Keen to stay on your branch and not fork.

**Comment by jrf0110** [comment]
Hey, @PaulGrimshaw thanks for pinging me again. Looking at it now

**Comment by jrf0110** [comment]
@PaulGrimshaw since this could be a breaking change, I went ahead and bumped to `v4.0.0` Thanks for the PR!

**Pull request merged**
