### PR TITLE
create table default helper supports value, string, function

### PR DESCRIPTION
**Pull request by newlix**

### CODE REVIEW

**Comment by jrf0110** [comment]
Hey, @newlix thanks for the PR. Everything is looking good, but I'll look at this further tonight

**Comment by newlix** [comment]
I just found in a dirac test case.
```javascript
dirac.register({
              name: 'users'
            , schema: {
                id: {
                  type: 'serial'
                , primaryKey: true
                }
              , other: { type: 'text' }
              , name: { type: 'text', default: "'poop'" }
              }
            });
```
It seems Mosql expect a text default to be "'sting'" but "string". 
It is better than my implement to guess if the string is a function expression or just a string default.
Please discard this pr and document this behavior.
Thank you!

**Comment by jrf0110** [comment]
Well, I do think it's within the domain of MoSQL to try and detect what type the output should be. There has a been a convention in the past for strings (for joining) to surround the string with `$` and `$` to indicate that the string should not be quoted - Perhaps we can do that here as well (if we wanted to support type detection)?

**Comment by jrf0110** [comment]
But, we should definitely document `default` behavior better

**Comment by newlix** [comment]
Actually MoSQL can't really detect a string either a function expression or a string without the user hint. 
In this situation, I think the current implement is better. 
default:"now()" => function expression
default:"'now()'"  => string
default:1          => value 
The '$xxxx$' used in joining indicates much more than the quote of a string.
```javascript
//without  $...$
//left join "usersBooks" on "usersBooks"."userId" = $1
{
      type: 'left'
    , target: "usersBooks"
    , on: { userId: 'users.id' }
    }
//with $....$
//left join "usersBooks" on "usersBooks"."userId" = "users"."id"
{
      type: 'left'
    , target: "usersBooks"
    , on: { userId: '$users.id$' }
    }
```

**Comment by jrf0110** [comment]
Well, I'd say in the case of booleans and numbers, you can safely not quote the value. All other values could be quoted by default unless surrounded with `$$`. However, I'm not sure if that really provides much usefulness (you either need to remember to quote yourself or use $$, so what's the point?)

**Comment by jrf0110** [comment]
So yeah, I'll go ahead close this PR and document the existing behavior

**Pull request closed without merging**
