### PR TITLE
Skip undefined values in values object

### LINKED ISSUE #135: Ignore undefined values in insert objects
I think it would make sense for the values helper to filter out undefined values. Currently it treats them as `NULL` instead which can lead to some weird edge cases.

e.g.

```js
// CREATE TABLE person(
//   "name" string NOT NULL,
//   "status" string NOT NULL DEFAULT "alive"
// )

const linus = { name: 'Linus' }

const query = {
  type: 'insert',
  table: 'person',
  values: {
    name: linus.name,
    status: linus.status
  }
}
```

When running the `query` this will fail since the `values` object will still have the key `person.status`, but the value of it is `undefined`. The database will then reject the row since status is NULL, instead of using the default value of "alive". This is a bit confusing since in javascript there can be both the absence of a key, or a key with the value `undefined`, and both of these cases will give back the value `undefined`.

This could potentially be a breaking change, but I would rather consider the current implementation a bug since I couldn't find it documented anywhere. I think that the least amount of surprise here is to get the default value when you omit a value.

I would be happy to submit a PR :)

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #135

### CODE REVIEW

**Comment by jrf0110** [comment]
Awesome. This is definitely the behavior we want (I've been meaning to do this for a while).

**Comment by jrf0110** [comment]
Beautiful. Thanks @LinusU

**Comment by LinusU** [comment]
Thank you!! This is an awesome library

**Comment by jrf0110** [comment]
I appreciate it :) It's long overdue for a re-write, though.

**Comment by jrf0110** [comment]
Published `mongo-sql@2.7.6`

**Pull request merged**
