### PR TITLE
Added $exists and $notExists conditional helpers

### LINKED ISSUE #68: Conditional Helpers: $exists, $notExists

### PR DESCRIPTION
**Pull request by doniyor2109**
Closes #68

### CODE REVIEW

**Comment by jrf0110** [comment]
Hey, it has tests and everything!

**Comment by jrf0110** [comment]
Oh shoot. @doniyor2109 would you mind submitting a followup PR that adds these helpers to the docs?

**Comment by jrf0110** [comment]
Published `mongo-sql@5.0.2`

**Comment by doniyor2109** [comment]
Sure, I will add usage and details in the docs

**Comment by doniyor2109** [comment]
Here is pull request #170 for documentation

**Pull request merged**
