### PR TITLE
Order tests added

### PR DESCRIPTION
**Pull request by PaulGrimshaw**

### CODE REVIEW

**Comment by jrf0110** [comment]
What I'd really like to see is the following:

```javascript
// order by "table"."col1" asc, "table"."col2" desc
{ order: [['col1', 'asc'], ['col2', 'desc']] }
// Or
// order by "table"."col1", "table"."col2" desc
{ order: ['col1', ['col2', 'desc'] }
```

**Comment by PaulGrimshaw** [comment]
Nice.  Is a nested array neccessary though, or could it also work with an object:

```
// order by "table"."col1" asc, "table"."col2" desc
{ order: [{'col1':'asc'}, {'col2':'desc'}] }

// Or
// order by "table"."col1", "table"."col2" desc
{ order: ['col1', {'col2':'desc'}] }
```

**Comment by PaulGrimshaw** [comment]
(Please note, this pull request only adds tests for the existing behaviour)

**Comment by jrf0110** [comment]
> Nice. Is a nested array neccessary though, or could it also work with an object:

I'm not exactly sure what the best solution is. I think if the goal is to make it easy and predictable to read the values from the query, then the array syntax provides a slightly easier way to enumerate:

```javascript
query.order.map(([col, direction]) => {
  console.log(col, direction)
})
```

Whereas getting the values from the array object syntax is clumsier:

```javascript
query.order.map(order => {
  for (let col in order) console.log(col, order[col])
})
```

I think what I'd want to do is enforce the use of the array syntax (thinking of `order` as an array of tuples `[column, direction]`) that way accessing these values is consistent

**Comment by PaulGrimshaw** [comment]
Works for me. In my project i have added a layer to throw an exception if a developer uses strings for order.

**Pull request merged**
