### PR TITLE
Skip undefined values in where object

### LINKED ISSUE #132: Ignore undefined values in where objects
I think it would make sense for the where helper to filter out undefined values. Currently it throws `TypeError: Cannot read property '0' of undefined`.

e.g.

```js
const filters = {
  age: { $gte: 40 }
}

const query = {
  type: 'select',
  table: 'person',
  where: {
    'person.id': filters.id,
    'person.name': filters.name,
    'person.age': filters.age
  }
}
```

When running the `query` this will fail since the `where` object will still have the keys `person.id` and `person.age`, but the value of them is `undefined`. This is a bit confusing since in javascript there can be both the absence of a key, or a key with the value `undefined`, and both of these cases will give back the value `undefined`.

I would be happy to submit a PR :)

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #132

### CODE REVIEW

**Comment by pinn3** [comment]
LGTM 🎉

**Comment by jrf0110** [comment]
So amazing! I've been wanting to fix this for a long time

**Comment by jrf0110** [comment]
Published at [v2.7.5](https://www.npmjs.com/package/mongo-sql)

**Comment by LinusU** [comment]
Thank you for the quick pull! :)

**Pull request merged**
