### PR TITLE
Added $not functionality

### PR DESCRIPTION
**Pull request by PaulGrimshaw**
I added some basic functionality to cover $not.  However, can't say i fully understand what is going on, and relied heavily on the 3 tests i wrote.  May need further enhancement for more complex scenarios.

### CODE REVIEW

**Comment by jrf0110** [comment]
@PaulGrimshaw this is so cool that it works at all :D Thank you! I need you to add the documentation for this helper as well

**Comment by jrf0110** [comment]
Closes #157

**Comment by PaulGrimshaw** [comment]
Added a section to the docs for $not

**Comment by jrf0110** [comment]
Published `mongo-sql@4.0.2`

**Comment by PaulGrimshaw** [comment]
Sorry, bit think I made a mistake on how $not should be used. Would be silly to deviate from mongo. I will correct asap so hopefully you can avoid a breaking change

**Pull request merged**
