### PR TITLE
Fix null handling in condition builder so we get the right equality/inequality descriptors

### PR DESCRIPTION
**Pull request by jrf0110**
Entering the following mongo-sql query results in an unexpected query:
```json
{
  "type": "select",
  "table": "users",
  "where": {
    "email": { "$ne": null }
  }
}
```

Expected result:
```sql
select "users".* from "users" where "users"."email" is not null
```

Actual result:
```sql
select "users".* from "users" where "users"."email" is null
```

### CODE REVIEW

**Comment by jrf0110** [comment]
Sorry for the late reply @johansteffner

I've converted this issue into a Pull Request that fixes the bug. This will be in npm at `mongo-sql@3.0.1`

**Comment by jrf0110** [comment]
Actually, this change could mean breaking changes for folks that relied on something like the following:

```javascript
where: {
  name: {
    $gt: null
  }
}
```

To produce:

```sql
where name is null
```

However, if we consider that behavior a bug and not a feature, then we can still get away with a patch release. The same query will now produce the slightly more desirable:

```sql
where name > null
```

Which, all-in-all, I'd say is easier to debug than the previous output

**Comment by jrf0110** [comment]
Working at `mongo-sql@3.0.1` See http://mosql.j0.hn/#/snippets/am

**Comment by johansteffner** [comment]
Great, thank you!

**Pull request merged**
